service: lambda-sns-slackbot

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

functions:
  sendToSns:
    handler: lambdas/sendToSns.handler
    onError: !Ref ErrorTopic

  sendToSlack:
    handler: lambdas/sendToSlack.handler
    events:
      - sns: ErrorTopic
    environment:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

resources:
  Resources:
    ErrorTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: error-notifications